name: Deploy to EC2

on:
  push:
    branches:
      - master # Despliega solo cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: deploy Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:  34.201.117.204
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /prueba1/
            git pull https://github.com/DanielCLa98/individual_ec2.git
            sudo systemctl restart httpd
          debug: true